language: scala

scala:
- 2.12.5

jdk:
- oraclejdk8

before_install:
- git fetch --tags
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.3.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.3

stages:
  - name: format
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


jobs:
  include:
    - stage: format
      script: sbt scalafmt::test
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage +coreJVM/test +circeJVM/test +fastJVM/test coverageReport
        - sbt validateDoc validateScalafmt
        - sbt example/compile
    - stage: release
      script: sbt ci-release



after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi


env:
  matrix:
    secure: POBj/u4+QKXoN+VUVfU1WqLM8+wqSdUG43hw+pss4+r00gS6kjftmHQk7GDC2fDRk+PLYWYI7oeenweYM0Y1Pktsn5cLzLAT8955LFGwIleWdxWva/knl+McP6tjPg0222PG1X7RXfQHtnncK9r2CR74c44jh6UbE2ol3BLKZbhxu9lJ81tK5aR1AAj1Bqr7kKaI2UuPlEhXGEgYx+Md5h3nakQKgb8tG9RjHe2VYREjQ/ynCxF796Z0Bah2OGPARiyhkwuzEauz2D7Skv84Xqj1DV7xcHALvSwfhvAIkGRhWGLQnm53gljpQKuFWXIrtpT6mJD7CpEPtfbvBBH2TxuzuGJ+taojqDgilnyTW/XHY5aPzS/WwrtbS1X3NEMtUpyNH1oWU9HWIO5L9smrjGmjNSbBeYIMF+jqzKdjbLRCSAo7sUlm4fyJp+eZf8lge4POJnvcgWR8vsik9xWbG9c4bVVXxIyGj91lPnEGBBzQAKjlsjurzObnENj57AklJZlH3NYb464vYg9dt5h33gCrRoASjA78QTPS7vQYbZBYZDRy3f+Bp9WxeAYisYF7CGGVY7sVcNEFhEiB5a7B0Q2k3pqUdLyMmhT0coh79SM6nskfb0P6T8zPvHRbL/o+yDQFpNkL/fYwnYdhf/y8EyA5MhFSJnJRUq3xGmMQ02c=
